version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - db_data_mw2:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      PGPASSWORD: postgrespassword
    # ports:
    #   - "7777:5432"
  graphql-engine:
    image: hasura/graphql-engine:latest
    ports:
    - "3008:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey

volumes:
  db_data_mw2: